FROM eclipse-temurin:21-jdk

WORKDIR /app

COPY .mvn .mvn
COPY mvnw pom.xml ./
COPY src ./src

RUN chmod +x mvnw

EXPOSE 8081

ENTRYPOINT ["./mvnw", "spring-boot:run", "-Dspring-boot.run.main-class=discovery.ciscos.distlab4.NodeApplication"]
